### ISSUE TITLE
[TYS-1] Add icons to add favorite recomendation

### ISSUE THREAD

**Issue by bremade** [bremade/TrackYourStop#1]
### Description
When retrieving the recomendations for the favorite form the displayed stations are often not distiguishable. To enhance that the suiting transport type[s] should be displayed with the station name

### Tasks

- [x] Add transportation types to retrieved values
- [x] Create icons that represent the transportation types
- [x] Implement mapper for transportation type name to according icon
- [x] Add icon displayed next to the station name
