### ISSUE TITLE
[TYS-4] Display planned departure time and the delay seperatly

### ISSUE THREAD

**Issue by bremade** [bremade/TrackYourStop#4]
### Description
Currently the departure time displayed is the actual departure time already containing the delay. To improve this the planned departure time should be displayed instead and additionally the delay as seperate component.

### Tasks

- [ ] Retrieve the planned departure time from api
- [ ] Replace actual with planned departure time
- [ ] Add ui component for delay (+X or nothing if 0)
