### ISSUE TITLE
[TYS-8] Create general settings page

### ISSUE THREAD

**Issue by bremade** [bremade/TrackYourStop#8]
### Description
In order to add features to the settings a general page is needed. This page needs to be displayed on bottom app bar press.

### Tasks

- [x] Create new page
- [x] Enable routing to new page
- [x] Add design switch configurable
